### ISSUE TITLE
Issue with custom converter

### ISSUE THREAD

**Issue by Willaem** [catalystneuro/nwb-web-gui#51]
Hey!

I'm trying to use the nwb-web-gui with a custom converter. The converter is very simple and taken almost directly from the simple tutorial available in the nwb-conversion-tools github :
```python
class exempleImageConverter(NWBConverter):
    data_interface_classes = dict(
        TiffImaging=TiffImagingInterface
    )
```
I got 2 errors. The first was reported on [json-schema-to-dash-forms](https://github.com/catalystneuro/json-schema-to-dash-forms) where it belongs, but I wasn't able to fix the second one. I believe the error comes from the schema conversion, althrough I am not sure. Here is the traceback :

```python
Source data is valid!
172.16.11.240 - - [06/Aug/2021 14:43:54] "POST /converter/_dash-update-component HTTP/1.1" 500 -
Error on request:
Traceback (most recent call last):
  File "/home/willaem/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/home/willaem/.local/lib/python3.8/site-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/home/willaem/.local/lib/python3.8/site-packages/flask/app.py", line 2088, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/willaem/.local/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.handle_exception(e)
  File "/home/willaem/.local/lib/python3.8/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/willaem/.local/lib/python3.8/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/willaem/.local/lib/python3.8/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/willaem/.local/lib/python3.8/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/willaem/.local/lib/python3.8/site-packages/dash/dash.py", line 1096, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/willaem/.local/lib/python3.8/site-packages/dash/dash.py", line 1017, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/home/willaem/.local/lib/python3.8/site-packages/nwb_web_gui/dashapps/pages/converter/converter.py", line 361, in get_metadata
    self.metadata_forms.construct_children_forms()
  File "/home/willaem/.local/lib/python3.8/site-packages/json_schema_to_dash_forms/forms.py", line 666, in construct_children_forms
    iform = SchemaForm(
  File "/home/willaem/.local/lib/python3.8/site-packages/json_schema_to_dash_forms/forms.py", line 282, in __init__
    self.make_form(properties=schema['properties'])
  File "/home/willaem/.local/lib/python3.8/site-packages/json_schema_to_dash_forms/forms.py", line 299, in make_form
    item = SchemaForm(schema=v, key=k, parent_form=self)
  File "/home/willaem/.local/lib/python3.8/site-packages/json_schema_to_dash_forms/forms.py", line 282, in __init__
    self.make_form(properties=schema['properties'])
  File "/home/willaem/.local/lib/python3.8/site-packages/json_schema_to_dash_forms/forms.py", line 324, in make_form
    iform = SchemaForm(schema=schema, key=f'{k}-{index}', parent_form=self)
  File "/home/willaem/.local/lib/python3.8/site-packages/json_schema_to_dash_forms/forms.py", line 255, in __init__
    self.owner_class = schema.get('tag', '')
AttributeError: 'list' object has no attribute 'get'
```

Thanks in advance!

**Comment by luiztauffer** [comment]
Hey @Willaem 
thanks for reporting this error, it required small updates on `json-to-forms`  and `nwb-conversion-gui` and also fixes on `nwb-conversion-tools`. 
Could you please try the latest changes and let me know if that got solved for you? Here’s how you’d install the latest versions:
```
pip install -U nwb-web-gui
pip install -U json-schema-to-dash-forms 
pip install git+https://github.com/catalystneuro/nwb-conversion-tools.git@refs/pull/231/head 
```

I’ve also made a small improvement for testing the GUI using custom converters, no need to have them installed anymore. You could run the code below and it should work:
```python
from nwb_conversion_tools import NWBConverter, TiffImagingInterface
from nwb_web_gui import init_app
import os

class exempleImageConverter(NWBConverter):
    data_interface_classes = dict(
        TiffImaging=TiffImagingInterface
    )
    
# Run app
os.environ['NWB_GUI_ROOT_PATH'] = '.'
app = init_app(converter_class=exempleImageConverter)
app.run()
```

**Comment by Willaem** [comment]
Hey @luiztauffer ! Sorry for the long delay, studies were getting started in the new semester.
The new version has been working great for that, thanks!
